export const DEFAULT_QUESTIONS = [
  {
    id: "q1",
    type: "single",
    category: "ARBEITSBEREICH",
    question: "In welchem Bereich arbeitest du hauptsächlich?",
    subtitle: null,
    options: [
      "Wareneingang / Sample Management",
      "Set-Vorbereitung / Styling",
      "Studio / Shooting",
      "Post-Production / Retusche",
      "Rückversand / Logistik",
      "Übergreifend / Koordination",
    ],
    rating_items: [],
    placeholder: null,
    sort_order: 1,
    is_required: true,
  },
  {
    id: "q2",
    type: "single",
    category: "ERFAHRUNG",
    question: "Wie lange arbeitest du bereits bei Orendt Studios?",
    subtitle: null,
    options: [
      "Weniger als 6 Monate",
      "6 Monate – 1 Jahr",
      "1 – 3 Jahre",
      "Mehr als 3 Jahre",
    ],
    rating_items: [],
    placeholder: null,
    sort_order: 2,
    is_required: true,
  },
  {
    id: "q3",
    type: "multiple",
    category: "ZEITFRESSER",
    question: "Bei welchen Arbeitsschritten verlierst du am meisten Zeit?",
    subtitle: "Mehrfachauswahl möglich",
    options: [
      "Samples suchen / identifizieren",
      "Auf Informationen warten",
      "Manuelle Dateneingabe (Excel, Listen)",
      "Abstimmung mit anderen Abteilungen",
      "Fehlerhafte / fehlende Lieferungen klären",
      "Rückversand vorbereiten & koordinieren",
      "Priorisierung der Aufträge",
    ],
    rating_items: [],
    placeholder: null,
    sort_order: 3,
    is_required: true,
  },
  {
    id: "q4",
    type: "rating",
    category: "BEWERTUNG",
    question: "Wie bewertest du die folgenden Bereiche?",
    subtitle: "1 = sehr schlecht, 5 = sehr gut",
    options: [],
    rating_items: [
      "Klarheit der Aufgabenverteilung",
      "Verfügbarkeit von Informationen",
      "Kommunikation zwischen Teams",
      "Zustand der Tools/Software",
      "Übersicht über Sample-Standorte",
    ],
    placeholder: null,
    sort_order: 4,
    is_required: false,
  },
  {
    id: "q5",
    type: "single",
    category: "KOMMUNIKATION",
    question: "Wie erfährst du meistens, was als nächstes zu tun ist?",
    subtitle: null,
    options: [
      "Mündlich / Zuruf",
      "E-Mail",
      "WhatsApp / Messenger",
      "Digitales System (z.B. CreativeForce)",
      "Ausgedruckte Listen / Zettel",
      "Ich muss selbst nachfragen",
    ],
    rating_items: [],
    placeholder: null,
    sort_order: 5,
    is_required: true,
  },
  {
    id: "q6",
    type: "single",
    category: "FRUSTRATION",
    question: "Was nervt dich im Arbeitsalltag am meisten?",
    subtitle: null,
    options: [
      "Unklare Zuständigkeiten",
      "Fehlende oder veraltete Informationen",
      "Zu viele manuelle Schritte",
      "Samples die nicht auffindbar sind",
      "Ständig wechselnde Prioritäten",
      "Mangelnde Kommunikation",
    ],
    rating_items: [],
    placeholder: null,
    sort_order: 6,
    is_required: true,
  },
  {
    id: "q7",
    type: "text",
    category: "DEINE IDEE",
    question: "Wenn du einen Prozess sofort ändern könntest – welcher wäre es und warum?",
    subtitle: null,
    options: [],
    rating_items: [],
    placeholder: "Beschreibe hier, was du ändern würdest...",
    sort_order: 7,
    is_required: false,
  },
  {
    id: "q8",
    type: "text",
    category: "FEEDBACK",
    question: "Gibt es noch etwas, das du uns mitteilen möchtest?",
    subtitle: null,
    options: [],
    rating_items: [],
    placeholder: "Dein zusätzliches Feedback...",
    sort_order: 8,
    is_required: false,
  },
]
